name: Run tests and deploy

on:
  push:
    branches:
      - main
jobs:
  deploy-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install serverless
        run: npm install -g serverless
        
      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
      - name: Deploy
        env:
          AUTH0_AUDIENCE: ${{ secrets.AUTH_AUDIENCE }}
          AUTH0_JWKS_URL: https://dev-f-g2ys78.us.auth0.com/.well-known/jwks.json
        run: cd serverless && sls deploy

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest requests
      - name: Run test
        env:
          AUTH0_AUDIENCE: ${{ secrets.AUTH_AUDIENCE }}
          AUTH0_CLIENT_ID: ${{ secrets.AUTH_CLIENT_ID }}
          AUTH0_CLIENT_SECRET: ${{ secrets.AUTH_CLIENT_SECRET }}
          AUTH0_TOKEN_REQUEST_URL: ${{ secrets.AUTH_TOKEN_REQUEST_URL }}
          ENDPOINT_URL: https://33ed3x1zug.execute-api.ap-northeast-1.amazonaws.com/dev/coffee_note
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
        run: |
          pytest tests/test_coffee_note.py -v

